AllCops:
  Include:
    - Berksfile
    - Gemfile
    - Rakefile
    - Thorfile
    - Guardfile
  Exclude:
    - vendor/**/*
    - libraries/**/*
    - providers/**/*

ClassLength:
  Enabled: false
Documentation:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
SignalException:
  Enabled: false
TrailingCommaInLiteral:
  Enabled: false
TrailingCommaInArguments:
  Enabled: false
WordArray:
  Enabled: false
